runtime: nodejs
env: flexible
beta_settings:
  cloud_sql_instances: buy-and-sell-48147:europe-central2:buy-and-sell-db
env_variables:
  DB_USER: hapi-server
  DB_PASS: 1QRtana1234!
  DB_NAME: buy-and-sell
  DB_SOCKET: /cloudsql/buy-and-sell-48147:europe-central2:buy-and-sell-db
